### ISSUE TITLE
After fileUpload project set up, gives 404 error.

### ISSUE THREAD

**Issue by skarthik85** [jdmr/fileUpload#1]
THe web.xml doesnot contain any serlvet defintions to load springs related classes. Once i set up the maven project with the files, on acessing URL localhost:8080, tomcat gives 404 error. Please check did you miss commiting any entries in web.xml or missed any beans xmls. Or am i missing something. Please advise.

**Comment by jdmr** [comment]
The spring configuration is handled by the classes in the config package. I've updated the project to work with the latest release of @blueimp. You can download the project and run it with mvn tomcat7:run
