### ISSUE TITLE
IE8 -  Internet Explorer cannot download PostFormData from ...

### ISSUE THREAD

**Issue by abazanov** [jdmr/fileUpload#2]
I have implemented the basic model of this uploader. Works in IE9 and 10, but not in IE8. I get the attached error. Not sure what to do.

Hope someone can help me.
Thanks

![ie8 error](https://f.cloud.github.com/assets/5940942/1714170/d19b738c-619c-11e3-974d-556561779d14.png)

**Comment by jdmr** [comment]
You have to post that question to the creator of the tool, I just implemented the server version with java.
